# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1102, 557)
        Form.setMinimumSize(QtCore.QSize(1102, 557))
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Riffic Free Medium\";")
        self.titlebar = QtWidgets.QFrame(Form)
        self.titlebar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.label = QtWidgets.QLabel(self.titlebar)
        self.label.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.label.setStyleSheet("background-color: #0a0000;\n"
"border-bottom:2px solid #cb213c;\n"
"border-top-left-radius:6px;\n"
"border-top-right-radius:6px;\n"
"font-size:15px;")
        self.label.setObjectName("label")
        self.icon = QtWidgets.QLabel(self.titlebar)
        self.icon.setGeometry(QtCore.QRect(0, 0, 21, 21))
        self.icon.setText("")
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.mini_but = QtWidgets.QPushButton(self.titlebar)
        self.mini_but.setGeometry(QtCore.QRect(1050, 1, 24, 17))
        self.mini_but.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid #cb213c;\n"
"border-radius:2px;")
        self.mini_but.setObjectName("mini_but")
        self.close_but = QtWidgets.QPushButton(self.titlebar)
        self.close_but.setGeometry(QtCore.QRect(1075, 1, 24, 17))
        self.close_but.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid #cb213c;\n"
"border-radius:2px;")
        self.close_but.setObjectName("close_but")
        self.main = QtWidgets.QFrame(Form)
        self.main.setGeometry(QtCore.QRect(0, 20, 1104, 537))
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.bg = QtWidgets.QLabel(self.main)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1102, 537))
        self.bg.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.501, cy:1, radius:0.822, fx:0.501, fy:1, stop:0 rgba(54, 26, 27, 255), stop:1 rgba(10, 0, 0, 255));\n"
"border-bottom-left-radius:6px;\n"
"border-bottom-right-radius:6px;")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.logo = QtWidgets.QLabel(self.main)
        self.logo.setGeometry(QtCore.QRect(456, 0, 191, 191))
        self.logo.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label_2 = QtWidgets.QLabel(self.main)
        self.label_2.setGeometry(QtCore.QRect(10, 6, 431, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.main)
        self.label_3.setGeometry(QtCore.QRect(662, 8, 431, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.inactive_mods = QtWidgets.QListWidget(self.main)
        self.inactive_mods.setGeometry(QtCore.QRect(662, 42, 431, 481))
        self.inactive_mods.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid #ce273e;\n"
"border-radius:6px;")
        self.inactive_mods.setObjectName("inactive_mods")
        self.right_but = QtWidgets.QPushButton(self.main)
        self.right_but.setGeometry(QtCore.QRect(470, 209, 161, 71))
        self.right_but.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.right_but.setText("")
        self.right_but.setObjectName("right_but")
        self.rightbg_image = QtWidgets.QLabel(self.main)
        self.rightbg_image.setGeometry(QtCore.QRect(470, 209, 161, 71))
        self.rightbg_image.setText("")
        self.rightbg_image.setScaledContents(True)
        self.rightbg_image.setObjectName("rightbg_image")
        self.left_but = QtWidgets.QPushButton(self.main)
        self.left_but.setGeometry(QtCore.QRect(470, 320, 161, 71))
        self.left_but.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.left_but.setText("")
        self.left_but.setObjectName("left_but")
        self.leftbg_image = QtWidgets.QLabel(self.main)
        self.leftbg_image.setGeometry(QtCore.QRect(470, 320, 161, 71))
        self.leftbg_image.setText("")
        self.leftbg_image.setScaledContents(True)
        self.leftbg_image.setObjectName("leftbg_image")
        self.add_mod_but = QtWidgets.QPushButton(self.main)
        self.add_mod_but.setGeometry(QtCore.QRect(470, 430, 161, 71))
        self.add_mod_but.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.add_mod_but.setText("")
        self.add_mod_but.setObjectName("add_mod_but")
        self.add_mod_image = QtWidgets.QLabel(self.main)
        self.add_mod_image.setGeometry(QtCore.QRect(470, 430, 161, 71))
        self.add_mod_image.setText("")
        self.add_mod_image.setScaledContents(True)
        self.add_mod_image.setObjectName("add_mod_image")
        self.active_mods = QtWidgets.QListWidget(self.main)
        self.active_mods.setGeometry(QtCore.QRect(13, 41, 431, 481))
        self.active_mods.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:1px solid #ce273e;\n"
"border-radius:6px;")
        self.active_mods.setObjectName("active_mods")
        self.setting_cog = QtWidgets.QPushButton(self.main)
        self.setting_cog.setGeometry(QtCore.QRect(1058, 0, 41, 41))
        self.setting_cog.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/--/code/assets/cog.png);\n"
"background-size:cover;")
        self.setting_cog.setText("")
        self.setting_cog.setObjectName("setting_cog")
        self.bg.raise_()
        self.add_mod_image.raise_()
        self.leftbg_image.raise_()
        self.rightbg_image.raise_()
        self.logo.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.inactive_mods.raise_()
        self.right_but.raise_()
        self.left_but.raise_()
        self.add_mod_but.raise_()
        self.active_mods.raise_()
        self.setting_cog.raise_()
        self.settings_bg = QtWidgets.QFrame(Form)
        self.settings_bg.setGeometry(QtCore.QRect(10000, 20, 1104, 537))
        self.settings_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_bg.setObjectName("settings_bg")
        self.grey_overlay = QtWidgets.QLabel(self.settings_bg)
        self.grey_overlay.setGeometry(QtCore.QRect(0, 0, 1101, 538))
        self.grey_overlay.setStyleSheet("background-color: rgba(0, 0, 0, 100);")
        self.grey_overlay.setText("")
        self.grey_overlay.setObjectName("grey_overlay")
        self.back_settings = QtWidgets.QPushButton(self.settings_bg)
        self.back_settings.setGeometry(QtCore.QRect(0, 0, 1101, 536))
        self.back_settings.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.back_settings.setText("")
        self.back_settings.setObjectName("back_settings")
        self.frame = QtWidgets.QFrame(self.settings_bg)
        self.frame.setGeometry(QtCore.QRect(350, 100, 401, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.settings_bg_label = QtWidgets.QLabel(self.frame)
        self.settings_bg_label.setGeometry(QtCore.QRect(0, 0, 401, 211))
        self.settings_bg_label.setStyleSheet("background-color: #0a0000;\n"
"border:1px solid #cb213c;\n"
"border-radius:6px;")
        self.settings_bg_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.settings_bg_label.setObjectName("settings_bg_label")
        self.game_path = QtWidgets.QLineEdit(self.frame)
        self.game_path.setGeometry(QtCore.QRect(40, 60, 231, 31))
        self.game_path.setStyleSheet("background-color: #1F1F1F;\n"
"border:1px solid #cb213c;\n"
"border-radius:6px;")
        self.game_path.setObjectName("game_path")
        self.browse_game_path = QtWidgets.QPushButton(self.frame)
        self.browse_game_path.setGeometry(QtCore.QRect(260, 60, 111, 31))
        self.browse_game_path.setStyleSheet("background-color:#cb213c;\n"
"border-radius:6px;\n"
"padding-left:10px;")
        self.browse_game_path.setObjectName("browse_game_path")
        self.motion_blur = QtWidgets.QPushButton(self.frame)
        self.motion_blur.setGeometry(QtCore.QRect(80, 140, 241, 31))
        self.motion_blur.setStyleSheet("background-color:#cb213c;\n"
"border-radius:6px;")
        self.motion_blur.setObjectName("motion_blur")
        self.settings_bg_label.raise_()
        self.browse_game_path.raise_()
        self.game_path.raise_()
        self.motion_blur.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "      Carts Of Glory Mod Loader"))
        self.mini_but.setText(_translate("Form", "-"))
        self.close_but.setText(_translate("Form", "x"))
        self.label_2.setText(_translate("Form", "ACTIVE MODS"))
        self.label_3.setText(_translate("Form", "I NACTIVE MODS"))
        self.settings_bg_label.setText(_translate("Form", "SETTINGS"))
        self.game_path.setPlaceholderText(_translate("Form", "Game Path"))
        self.browse_game_path.setText(_translate("Form", "Browse"))
        self.motion_blur.setText(_translate("Form", "patch to remove motion blur"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
